title: Matt Estrada
description: Research Scientist at the AI Institute
show_downloads: true
google_analytics: G-2XJKZPN8CJ
nav:
  - title: About
    url: /
  - title: Experience
    url: /pages/experience.html
  - title: Posts
    url: /pages/posts.html

plugins:
  - jekyll-seo-tag
